#!/usr/bin/env python3
"""
The score for What Maya Knew: five quiet cues for piano and strings.

The game had no music at all — only filtered noise under the reading. This
is a small score written note by note (below), played on recorded
instruments: the upright piano and string sections from VSCO 2 Community
Edition (CC0, Versilian Studios; piano sampled by Simon Dalzell of Ivy
Audio). Nothing is generated by a model.

One theme carries the game. It's Maya's: a falling line in D minor that
never quite settles. The investigation cue breaks it into fragments over a
cello pedal so it stays under the reading. The convergence cue drops the
tune and keeps a pulse. The ending plays it whole and stops on an open
fifth, neither major nor minor, because every ending is a little of both.

    .venv-tts/bin/python scripts/compose_score.py /path/to/VSCO-2-CE

Writes public/audio/mus-<cue>.mp4 (AAC; the Artifact host doesn't serve .m4a).
Each cue is a seamless loop: the render runs past the loop point and the
reverb tail is folded back over the head.
"""
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import soundfile as sf
from scipy.signal import fftconvolve

sys.path.insert(0, str(Path(__file__).resolve().parent))
from score_lib import SR, Instrument  # noqa: E402

VSCO = Path(sys.argv[1]) if len(sys.argv) > 1 else None
ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'public' / 'audio'
rng = np.random.default_rng(310)

NOTE = {'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11}


def m(name):
    """'D4' -> 62, 'Bb1' -> 34, 'C#4' -> 61"""
    mm = re.fullmatch(r'([A-G])([#b]?)(-?\d)', name)
    n = NOTE[mm.group(1)] + {'#': 1, 'b': -1, '': 0}[mm.group(2)]
    return 12 * (int(mm.group(3)) + 1) + n


# ── the instruments ──────────────────────────────────────────────────────

def read(p):
    x, sr = sf.read(p, dtype='float32')
    if x.ndim > 1: x = x.mean(1)
    if sr != SR:
        from scipy.signal import resample_poly
        x = resample_poly(x, SR, sr).astype('float32')
    return x


def piano(dyn):
    # MappingChart.txt: file index i is key 21 + 2i
    d = VSCO / 'Keys' / 'Upright Piano'
    out = []
    for p in sorted(d.glob(f'Player_dyn{dyn}_rr1_*.wav')):
        i = int(p.stem.split('_')[-1])
        out.append((min(21 + 2 * i, 108), read(p)))
    return Instrument(out, release=0.45)


def strings(folder, pattern):
    # VSCO names these an octave low; checked against a pitch tracker, every
    # file sounds twelve semitones above its name.
    out = []
    for p in sorted((VSCO / 'Strings' / folder).glob(pattern)):
        name = re.search(r'_([A-G]#?\d)_', p.name + '_').group(1)
        out.append((m(name) + 12, read(p)))
    return Instrument(out, release=1.4)


# ── rendering ────────────────────────────────────────────────────────────

class Track:
    def __init__(self, seconds):
        self.buf = np.zeros((int((seconds + 12) * SR), 2), dtype='float32')

    def add(self, inst, note, t, dur, vel, pan=0.0, jitter=0.012):
        t = max(0.0, t + rng.normal(0, jitter))
        vel = vel * (1 + rng.normal(0, 0.06))
        y = inst.note(m(note) if isinstance(note, str) else note, dur, vel)
        i = int(t * SR)
        n = min(len(y), len(self.buf) - i)
        L, R = np.cos((pan + 1) * np.pi / 4), np.sin((pan + 1) * np.pi / 4)
        self.buf[i:i + n, 0] += y[:n] * L
        self.buf[i:i + n, 1] += y[:n] * R


def room(seconds=3.4, darkness=0.9994):
    """A stereo hall: decorrelated noise that dies away and darkens as it goes."""
    n = int(seconds * SR)
    t = np.arange(n) / SR
    ir = np.zeros((n, 2), dtype='float32')
    for c in range(2):
        noise = rng.normal(0, 1, n).astype('float32')
        # one-pole lowpass whose cutoff falls with time
        y = np.zeros(n, dtype='float32'); acc = 0.0
        a = 0.2
        for k in range(0, n, 256):
            a = max(0.02, a * darkness ** 256)
            seg = noise[k:k + 256]
            for j, v in enumerate(seg):
                acc += a * (v - acc); y[k + j] = acc
        ir[:, c] = y * np.exp(-6.9 * t / seconds)
    ir[:int(0.012 * SR)] = 0                       # pre-delay
    return ir / np.sqrt((ir ** 2).sum(0, keepdims=True))      # unit energy per channel


IR = None


def finish(track, loop_s, wet=0.32, name='cue'):
    global IR
    if IR is None: IR = room()
    dry = track.buf
    wetsig = np.stack([fftconvolve(dry[:, c], IR[:, c])[:len(dry)] for c in range(2)], 1)
    mix = dry * (1 - wet) + wetsig * wet
    # fold everything past the loop point back over the head
    L = int(loop_s * SR)
    out = mix[:L].copy()
    tail = mix[L:]
    for k in range(0, len(tail), L):
        seg = tail[k:k + L]; out[:len(seg)] += seg
    # level: quiet bed under reading, peaks well clear of clipping
    rms = np.sqrt((out ** 2).mean())
    out *= 10 ** (-24 / 20) / (rms + 1e-9)
    pk = np.abs(out).max()
    if pk > 10 ** (-3 / 20): out *= 10 ** (-3 / 20) / pk
    print(f'{name:14s} {loop_s:6.1f}s  rms -24 dBFS  peak {20*np.log10(np.abs(out).max()):.1f} dBFS')
    return out


def write(name, x):
    wav = OUT / f'mus-{name}.wav'
    sf.write(wav, x, SR, subtype='PCM_16')
    mp4 = OUT / f'mus-{name}.mp4'
    subprocess.run(['afconvert', '-f', 'mp4f', '-d', 'aac', '-b', '112000', str(wav), str(mp4)], check=True)
    wav.unlink()


# ── the music ────────────────────────────────────────────────────────────
# Bars are in 4/4. Each bar: (left-hand arpeggio, right-hand melody), where
# a note is (name, beat, beats).

THEME_A = [
    # Dm
    ([('D2', 0, 4), ('A2', 1, 3), ('D3', 2, 2), ('F3', 3, 1)], [('A4', 0, 2), ('F4', 2, 1), ('E4', 3, 1)]),
    # Bbmaj7
    ([('Bb1', 0, 4), ('F2', 1, 3), ('D3', 2, 2), ('A3', 3, 1)], [('D4', 0, 3), ('F4', 3, 1)]),
    # F/A
    ([('A1', 0, 4), ('F2', 1, 3), ('C3', 2, 2), ('A3', 3, 1)], [('C5', 0, 2), ('A4', 2, 1), ('G4', 3, 1)]),
    # Csus2 -> C
    ([('C2', 0, 4), ('G2', 1, 3), ('D3', 2, 1), ('E3', 3, 1)], [('E4', 0, 4)]),
    # Gm
    ([('G1', 0, 4), ('D2', 1, 3), ('Bb2', 2, 2), ('D3', 3, 1)], [('D5', 0, 2), ('Bb4', 2, 1), ('A4', 3, 1)]),
    # Dm/F
    ([('F1', 0, 4), ('A2', 1, 3), ('D3', 2, 2), ('F3', 3, 1)], [('F4', 0, 3), ('A4', 3, 1)]),
    # Bb
    ([('Bb1', 0, 4), ('F2', 1, 3), ('Bb2', 2, 2), ('D3', 3, 1)], [('G4', 0, 1), ('F4', 1, 1), ('E4', 2, 1), ('D4', 3, 1)]),
    # A sus4 -> A
    ([('A1', 0, 4), ('E2', 1, 3), ('A2', 2, 2), ('E3', 3, 1)], [('D4', 0, 2), ('C#4', 2, 2)]),
]
ROOTS = ['D2', 'Bb1', 'A1', 'C2', 'G1', 'F2', 'Bb1', 'A1']          # cello, an octave up where it must
THIRDS = ['F3', 'D3', 'C3', 'E3', 'D3', 'A3', 'D3', 'C#3']          # viola pad, inside the viola's range


def play_bars(tr, bars, t0, beat, pno, vel_lh=0.28, vel_rh=0.42, rh_shift=0, rh=True):
    for b, (lh, mel) in enumerate(bars):
        bt = t0 + b * 4 * beat
        for n, at, d in lh:
            tr.add(pno, n, bt + at * beat, d * beat + 0.6, vel_lh * (1.1 if at == 0 else 0.9), pan=-0.15)
        if rh:
            for n, at, d in mel:
                tr.add(pno, m(n) + rh_shift, bt + at * beat, d * beat, vel_rh, pan=0.1)


def cue_theme(pno, cello, viola):
    """Menu and prologue: the theme, then again with strings under it, then a breath."""
    beat = 60 / 60
    bars = 20
    tr = Track(bars * 4 * beat)
    play_bars(tr, THEME_A, 0, beat, pno)
    play_bars(tr, THEME_A, 32 * beat, beat, pno, vel_rh=0.38)
    for b in range(8):
        t = (32 + 4 * b) * beat
        tr.add(cello, m(ROOTS[b]) + 12, t, 4 * beat, 0.16, pan=-0.35)
        tr.add(viola, THIRDS[b], t + 0.3, 3.6 * beat, 0.10, pan=0.35)
    # the breath: four bars of left hand only, the tune's first note floating
    coda = [THEME_A[0], THEME_A[1], THEME_A[4], THEME_A[7]]
    play_bars(tr, coda, 64 * beat, beat, pno, vel_lh=0.22, rh=False)
    tr.add(pno, 'A4', 64 * beat + 2 * beat, 3 * beat, 0.26, pan=0.1)
    tr.add(pno, 'E4', 76 * beat, 4 * beat, 0.22, pan=0.1)
    return finish(tr, bars * 4 * beat, name='theme')


def cue_apartment(pno):
    """Her flat: the first phrase, slower, alone, and then the room."""
    beat = 60 / 52
    bars = 12
    tr = Track(bars * 4 * beat)
    play_bars(tr, THEME_A, 0, beat, pno, vel_lh=0.22, vel_rh=0.30)
    tail = [THEME_A[0], THEME_A[1], THEME_A[4], THEME_A[7]]
    play_bars(tr, tail, 32 * beat, beat, pno, vel_lh=0.16, rh=False)
    return finish(tr, bars * 4 * beat, wet=0.4, name='apartment')


def cue_investigation(pno, cello, viola):
    """Under the reading. A cello pedal, a pad that comes and goes, and the
    theme in pieces, far apart, so it's there without asking for attention."""
    beat = 60 / 50
    bars = 32
    tr = Track(bars * 4 * beat)
    plan = ['D2', 'Bb1', 'G1', 'A1', 'D2', 'F2', 'Bb1', 'A1']        # four bars each
    pads = ['A3', 'F3', 'D3', 'E3', 'A3', 'C3', 'D3', 'C#3']
    for k, root in enumerate(plan):
        t = k * 16 * beat
        r = m(root) + 12 if m(root) < 36 else m(root)
        # the sample runs out around nine seconds, so re-bow halfway through
        tr.add(cello, r, t, 8 * beat, 0.15, pan=-0.3)
        tr.add(cello, r, t + 8 * beat - 0.4, 8 * beat + 0.4, 0.13, pan=-0.3)
        if k in (2, 3, 6, 7):
            tr.add(viola, pads[k], t + 2 * beat, 12 * beat, 0.08, pan=0.35)
        # a low piano note where the harmony moves
        tr.add(pno, m(root) - 12 if m(root) > 40 else m(root), t, 6 * beat, 0.16, pan=-0.1)
    frags = [
        (1, [('A4', 0, 2), ('F4', 2, 1), ('E4', 3, 4)]),
        (6, [('D5', 0, 1), ('C5', 1, 1), ('A4', 2, 5)]),
        (10, [('Bb4', 0, 2), ('A4', 2, 1), ('G4', 3, 4)]),
        (14, [('E4', 0, 2), ('C#4', 2, 5)]),
        (18, [('A4', 0, 2), ('F4', 2, 1), ('E4', 3, 1), ('D4', 4, 4)]),
        (22, [('F4', 0, 1), ('A4', 1, 1), ('C5', 2, 5)]),
        (26, [('D5', 0, 2), ('Bb4', 2, 5)]),
        (30, [('E4', 0, 3), ('D4', 3, 1), ('C#4', 4, 4)]),
    ]
    for bar, notes in frags:
        for n, at, d in notes:
            tr.add(pno, n, (bar * 4 + at) * beat, d * beat, 0.30, pan=0.12)
    return finish(tr, bars * 4 * beat, wet=0.42, name='investigation')


def cue_convergence(pno, cello, viola, violin):
    """The call is close. No tune: a pulse in the low strings, a heartbeat in
    the piano, and the violins climbing one step at a time."""
    beat = 60 / 76
    bars = 24
    tr = Track(bars * 4 * beat)
    upper = ['D3', 'D3', 'Eb3', 'D3']                                # the second cello's line, per bar
    for b in range(bars):
        t = b * 4 * beat
        for e in range(8):                                           # eighth notes, first of each pair leaning
            vel = 0.20 if e % 2 == 0 else 0.13
            vel *= 1 + 0.35 * (b / bars)
            tr.add(cello, 'D2' if b % 8 < 6 else 'C#2', t + e * beat / 2, beat * 0.32, vel, pan=-0.35, jitter=0.006)
        if b >= 8:
            tr.add(cello, upper[b % 4], t, 4 * beat, 0.10, pan=-0.2)
        # heartbeat
        tr.add(pno, 'D1', t, beat * 1.5, 0.30, pan=0, jitter=0.004)
        tr.add(pno, 'D2', t + 0.28, beat * 1.2, 0.18, pan=0, jitter=0.004)
    line = [('A4', 0, 8), ('Bb4', 8, 8), ('C#5', 16, 4), ('D5', 20, 4)]
    for n, start, length in line:
        for k in range(0, length, 2):                               # re-bow every two bars
            vel = 0.07 + 0.10 * ((start + k) / bars)
            tr.add(violin, n, (start + k) * 4 * beat, 8 * beat + 0.5, vel, pan=0.35)
    inner = [('F4', 0, 8), ('G4', 8, 8), ('E4', 16, 8)]
    for n, start, length in inner:
        for k in range(0, length, 2):
            tr.add(viola, n, (start + k) * 4 * beat + 0.2, 8 * beat + 0.4, 0.07, pan=0.2)
    return finish(tr, bars * 4 * beat, wet=0.3, name='convergence')


def cue_ending(pno, cello, viola, violin):
    """The theme whole, with strings, and a last chord that's an open fifth."""
    beat = 60 / 56
    bars = 20
    tr = Track(bars * 4 * beat)
    play_bars(tr, THEME_A, 0, beat, pno, vel_rh=0.40)
    for b in range(8):
        tr.add(cello, m(ROOTS[b]) + 12, (4 * b) * beat, 4 * beat, 0.12, pan=-0.35)
    play_bars(tr, THEME_A, 32 * beat, beat, pno, vel_rh=0.34, rh_shift=12)
    for b in range(8):
        t = (32 + 4 * b) * beat
        tr.add(cello, m(ROOTS[b]) + 12, t, 4 * beat, 0.16, pan=-0.35)
        tr.add(viola, THIRDS[b], t + 0.2, 3.8 * beat, 0.11, pan=0.3)
        tr.add(violin, THEME_A[b][1][0][0], t + 0.4, 3.4 * beat, 0.08, pan=0.4)
    # four bars on D and A, nothing between them
    t = 64 * beat
    for n, v in [('D2', 0.3), ('A2', 0.24), ('D3', 0.2), ('A3', 0.18), ('D4', 0.16)]:
        tr.add(pno, n, t, 12 * beat, v, pan=0)
    tr.add(pno, 'A4', t + 2 * beat, 10 * beat, 0.2, pan=0.1)
    tr.add(cello, 'D3', t, 9 * beat, 0.14, pan=-0.35)
    tr.add(viola, 'A3', t + 0.3, 9 * beat, 0.10, pan=0.3)
    tr.add(violin, 'D5', t + 0.6, 9 * beat, 0.06, pan=0.4)
    return finish(tr, bars * 4 * beat, wet=0.36, name='ending')


if __name__ == '__main__':
    only = set(sys.argv[2:])
    pno = piano(1)
    cello = strings('Cello Section/susvib', '*_v1_1.wav')
    viola = strings('Viola Section/susvib', '*_v1_1.wav')
    violin = strings('Violin Section/susVib', '*_v1.wav')
    cues = {
        'theme': lambda: cue_theme(pno, cello, viola),
        'apartment': lambda: cue_apartment(pno),
        'investigation': lambda: cue_investigation(pno, cello, viola),
        'convergence': lambda: cue_convergence(pno, cello, viola, violin),
        'ending': lambda: cue_ending(pno, cello, viola, violin),
    }
    for name, make in cues.items():
        if only and name not in only: continue
        write(name, make())
